export { default as Navbar }       from './Navbar'
export { default as Hero }         from './Hero'
export { default as StatsBar }     from './StatsBar'
export { default as Features }     from './Features'
export { default as HowItWorks }   from './HowItWorks'
export { default as AppShowcase }  from './AppShowcase'
export { default as Testimonials } from './Testimonials'
export { default as Pricing }      from './Pricing'
export { default as FinalCTA }     from './FinalCTA'
export { default as Footer }       from './Footer'

export type { NavbarProps, NavLink }       from './Navbar'
export type { HeroProps }                  from './Hero'
export type { StatsBarProps, Stat }        from './StatsBar'
export type { FeaturesProps, Feature }     from './Features'
export type { HowItWorksProps, Step }      from './HowItWorks'
export type { AppShowcaseProps }           from './AppShowcase'
export type { TestimonialsProps, Testimonial } from './Testimonials'
export type { PricingProps, Plan }         from './Pricing'
export type { FinalCTAProps }              from './FinalCTA'
export type { FooterProps, FooterGroup, FooterLink } from './Footer'
